/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TjansterIndexRouteImport } from './routes/tjanster.index'
import { Route as ProjektIndexRouteImport } from './routes/projekt.index'
import { Route as TjansterSlugRouteImport } from './routes/tjanster.$slug'
import { Route as ProjektSlugRouteImport } from './routes/projekt.$slug'

const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterIndexRoute = TjansterIndexRouteImport.update({
  id: '/tjanster/',
  path: '/tjanster/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektIndexRoute = ProjektIndexRouteImport.update({
  id: '/projekt/',
  path: '/projekt/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterSlugRoute = TjansterSlugRouteImport.update({
  id: '/tjanster/$slug',
  path: '/tjanster/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektSlugRoute = ProjektSlugRouteImport.update({
  id: '/projekt/$slug',
  path: '/projekt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/projekt/$slug': typeof ProjektSlugRoute
  '/tjanster/$slug': typeof TjansterSlugRoute
  '/projekt/': typeof ProjektIndexRoute
  '/tjanster/': typeof TjansterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/projekt/$slug': typeof ProjektSlugRoute
  '/tjanster/$slug': typeof TjansterSlugRoute
  '/projekt': typeof ProjektIndexRoute
  '/tjanster': typeof TjansterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/projekt/$slug': typeof ProjektSlugRoute
  '/tjanster/$slug': typeof TjansterSlugRoute
  '/projekt/': typeof ProjektIndexRoute
  '/tjanster/': typeof TjansterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/faq'
    | '/integritetspolicy'
    | '/kontakt'
    | '/om-oss'
    | '/projekt/$slug'
    | '/tjanster/$slug'
    | '/projekt/'
    | '/tjanster/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/faq'
    | '/integritetspolicy'
    | '/kontakt'
    | '/om-oss'
    | '/projekt/$slug'
    | '/tjanster/$slug'
    | '/projekt'
    | '/tjanster'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/faq'
    | '/integritetspolicy'
    | '/kontakt'
    | '/om-oss'
    | '/projekt/$slug'
    | '/tjanster/$slug'
    | '/projekt/'
    | '/tjanster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  ProjektSlugRoute: typeof ProjektSlugRoute
  TjansterSlugRoute: typeof TjansterSlugRoute
  ProjektIndexRoute: typeof ProjektIndexRoute
  TjansterIndexRoute: typeof TjansterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/': {
      id: '/tjanster/'
      path: '/tjanster'
      fullPath: '/tjanster/'
      preLoaderRoute: typeof TjansterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/': {
      id: '/projekt/'
      path: '/projekt'
      fullPath: '/projekt/'
      preLoaderRoute: typeof ProjektIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/$slug': {
      id: '/tjanster/$slug'
      path: '/tjanster/$slug'
      fullPath: '/tjanster/$slug'
      preLoaderRoute: typeof TjansterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/$slug': {
      id: '/projekt/$slug'
      path: '/projekt/$slug'
      fullPath: '/projekt/$slug'
      preLoaderRoute: typeof ProjektSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  ProjektSlugRoute: ProjektSlugRoute,
  TjansterSlugRoute: TjansterSlugRoute,
  ProjektIndexRoute: ProjektIndexRoute,
  TjansterIndexRoute: TjansterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
